### ISSUE TITLE
Bug Fixing: Add primary key annotations to Common's entities

### ISSUE THREAD

**Issue by BlackBear2003** [BlackBear2003/FoodIntellectuals#2]
粗心的zzz在上一个任务中忘记给实体类的主键加上声明其主键策略的注解，将会导致无法加载到数据库自增的主键ID值。

请查看数据库设计图，将需要被标记的主键缺失的注解添加上！

missing：
![image](https://github.com/BlackBear2003/FoodIntellectuals/assets/94302726/f72c01c9-36a7-4917-b0e6-13393c58fffd)

correct：
![image](https://github.com/BlackBear2003/FoodIntellectuals/assets/94302726/d672d18f-045d-4552-b574-abf834da4d1d)

**Comment by smmdtgxx** [comment]
我来了我来了

**Comment by BlackBear2003** [comment]
> 我来了我来了

😃🫡

**Comment by BlackBear2003** [comment]
nice job!
